# Generated by Django 4.1.3 on 2023-02-13 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='menu5',
        ),
    ]
